### ISSUE TITLE
How do I use this in Unity?

### ISSUE THREAD

**Issue by theonerm2** [MeltyPlayer/libsm64-sharp#1]
I'm unsure how I could use this in Unity or even as to why I'd want to.

**Comment by MeltyPlayer** [comment]
Actually, you probably *don’t* want to use this in Unity, since there’s already a better library for doing that:
https://github.com/libsm64/libsm64-unity

This library is primarily for people who want to work in C# without going through Unity.

**Comment by theonerm2** [comment]
Actually I had been trying to do things with that library that I couldn't do. I had made a custom dll version of it that allowed me to use a different model for Mario but I lost the dll because I stupidly overwrote it with a modified version of the latest one and it didn't work anymore for the extra functions due to a change in the API. I didn't have a backup. I looked at this and I thought maybe it could be used to make a Mario 64 Library to do additional functions in Unity.
